version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongodb-net

networks:
  mongodb-net:
    external: true

